#!/bin/bash
# depends: curl getopt rsync
#
# Author: muink
# Github: https://github.com/muink/luci-app-packagesync
#

# Info
PKGNAME='packagesync'
VERSION="20230211"
#
DEF_HOMEURL="packagesync"
DEF_HOMEPATH="/www/$DEF_HOMEURL"
# url path
OPENWRT_URL="https://downloads.openwrt.org"
URLHREF_RELEASES='releases'
URLHREF_SNAPSHOTS='snapshots'
URLHREF_PACKAGES_PREFIX='packages-' # packages-22.03
URLHREF_VERS_PACKAGES='packages'
URLHREF_VERS_TARGETS='targets'


